Removed tcsh scripts and other small fixes

diff --git a/deps/install_pytables b/deps/install_pytables
--- a/deps/install_pytables
+++ b/deps/install_pytables
@@ -1,13 +1,9 @@
-#!/bin/tcsh
-
+#!/bin/bash
+set -ex
 ## PyTables cannot handle separate locations --prefix --exec-prefix
 ## in its dependencies, so we do not use --exec-prefix
 
-set curdir=`pwd`
-
-#goto pytables
-
-szip:
+curdir=`pwd`
 
 cd szip
 make clean
@@ -24,8 +20,6 @@ make && \
 make install
 cd $curdir
 
-lzo:
-
 cd lzo
 make clean
 ./configure --prefix=$INSTMACH --with-pic && \
@@ -34,23 +28,15 @@ make install
 #ln -s $INSTMACH/lib/liblzo2.a $INSTMACH/lib/liblzo.a
 cd $curdir
 
-#lzop:
-
 #setenv CFLAGS "$CFLAGS -I$INSTMACH/include/lzo"
 #setenv CPPFLAGS "$CPPFLAGS -I$INSTMACH/include/lzo"
 
-pytables:
-
-if ( $?LD_RUN_PATH ) then
-	setenv LD_RUN_PATH ""
-endif
-setenv LD_RUN_PATH $INSTMACH/lib
-
+export LD_RUN_PATH="$LD_RUN_PATH:$INSTMACH/lib"
 cd tables
 rm -rf build
-set PYTAB_SETUP_ARGS="--hdf5=$INSTMACH --lzo=$INSTMACH"
+PYTAB_SETUP_ARGS="--hdf5=$INSTMACH --lzo=$INSTMACH"
 python setup.py $PYTAB_SETUP_ARGS build_ext --inplace && \
 python setup.py $PYTAB_SETUP_ARGS install --prefix=$INST --exec-prefix=$INSTMACH && \
-python -m tables -c 'tables.test()'
-#somehow test just silently does nothing when run like above, but works if run interactively
+python -c 'import tables; tables.test()'
+#somehow python -m tables -c 'tables.test()' test just silently does nothing
 
diff --git a/deps/install_stage_2 b/deps/install_stage_2
--- a/deps/install_stage_2
+++ b/deps/install_stage_2
@@ -1,21 +1,23 @@
 #!/bin/bash
-set -ex #abort if any command fails and echo all commands
+set -e#abort if any command fails and echo all commands
+set -x
 topdir=$(pwd)
 if false; then
 bash setuptools/setuptools-0.6c9-py2.5.egg 
 easy_install --upgrade mercurial
 cd git/git && ${topdir}/install_git && cd ${topdir}
-cd cmake/cmake && ${topdir}/install_cmake && cd ${topdir}
+cd cmake && ${topdir}/install_cmake && cd ${topdir}
 cd mysql/mysql && ${topdir}/install_mysql && cd ${topdir}
 cd egenix/egenix-mx-base && ${topdir}/install_egenix && cd ${topdir}
 cd numpy/numpy && ${topdir}/install_numpy && cd ${topdir}
-cd pymol && ${topdir}/install_pymol && cd ${topdir}
+#cd pymol && ${topdir}/install_pymol && cd ${topdir}
 cd reportlab/reportlab && ${topdir}/install_reportlab && cd ${topdir}
 cd biopython/biopython && ${topdir}/install_biopython && cd ${topdir}
 cd boost/boost && ${topdir}/install_boost && cd ${topdir}
 cd matplotlib/matplotlib && ${topdir}/install_matplotlib && cd ${topdir}
 cd mysql/MySQL-python/MySQL-python && ${topdir}/install_pymysql && cd ${topdir}
 cd pytables && ${topdir}/install_pytables && cd ${topdir}
+fi
 easy_install --upgrade bx-python
 easy_install --upgrade ipython
 #A simple easy_install call below should work, but it does not. So we use specific tarball link.
@@ -26,6 +28,5 @@ easy_install --upgrade http://downloads.sourceforge.net/project/mdp-toolkit/mdp-
 cd swig/swig && ${topdir}/install_swig && cd ${topdir}
 cd numpy/numpy && ${topdir}/install_numpy && cd ${topdir}
 cd shogun/shogun/src && ${topdir}/install_shogun && cd ${topdir}
-fi
 cd genometools/genometools && ${topdir}/install_genometools && cd ${topdir}
 
