Script to install python 2.6 with executable suffix

diff --git a/deps/install_stage_2 b/deps/install_stage_2
--- a/deps/install_stage_2
+++ b/deps/install_stage_2
@@ -1,8 +1,7 @@
 #!/bin/bash
-set -e#abort if any command fails and echo all commands
-set -x
+set -ex #abort if any command fails and echo all commands
 topdir=$(pwd)
-if false; then
+#if false; then
 bash setuptools/setuptools-0.6c9-py2.5.egg 
 easy_install --upgrade mercurial
 cd git/git && ${topdir}/install_git && cd ${topdir}
@@ -17,7 +16,7 @@ cd boost/boost && ${topdir}/install_boost && cd ${topdir}
 cd matplotlib/matplotlib && ${topdir}/install_matplotlib && cd ${topdir}
 cd mysql/MySQL-python/MySQL-python && ${topdir}/install_pymysql && cd ${topdir}
 cd pytables && ${topdir}/install_pytables && cd ${topdir}
-fi
+#fi
 easy_install --upgrade bx-python
 easy_install --upgrade ipython
 #A simple easy_install call below should work, but it does not. So we use specific tarball link.
